server.port=8087


spring.thymeleaf.cache=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# MySQL ?????? ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/auction?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=rlaekdud

# JPA ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto= update



spring.redis.host=localhost
spring.redis.port=6379




logging.level.org.hibername.SQL = debug
logging.level.org.hibernate.type.descriptor.sql= trace

#jwt
JWT_TOKEN=1083c1b56e7981420b9c455b2b3d6c8a2df615b1b7e14b0b871a4e5c218069ac
jwt.header=Authorization
jwt.token-validity-in-seconds=86400

JWT_EXPIRE_TIME=3600000

#Redis
redis.host=127.0.0.1
redis.port=6379

spring.jackson.serialization.fail-on-empty-beans=false
